dist: xenial
language: python
cache: pip
python:
  - "3.7.3"
install:
  - pip install -r requirements.txt
before_script:
  - cp settings_local.py.template settings_local.py
script:
  - python manage.py test
